# Generated by Django 2.1.5 on 2019-06-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_cartitem_line_item_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=19.9, max_digits=12),
            preserve_default=False,
        ),
    ]
